---
# vars file for docker
_docker_packages:
  default:
    - docker
    - docker-compose
  Alpine:
    - docker
  RedHat-7:
    - docker-io
    - docker-compose
  RedHat-8:
    - podman-docker
  Debian:
    - docker.io
    - docker-compose
  Fedora-29:
    - podman-docker
  Fedora-30:
    - podman-docker
  Fedora-31:
    - podman-docker


docker_packages: "{{ _docker_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_docker_packages[ansible_distribution] | default(_docker_packages['default'])) }}"

docker_pip_packages:
  - docker
  - docker-compose

_docker_service:
  default: docker
  RedHat-8: io.podman
  Fedora-29: io.podman
  Fedora-30: io.podman
  Fedora-31: io.podman

docker_service: "{{ _docker_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_docker_service['default']) }}"
